### ISSUE TITLE
docker set up script crashes when trying to setup database

### ISSUE THREAD

**Issue by nresh** [datafruits/streampusher-api#122]
I get an error when I run the script needed to get the docker container running with rails, postgres, redis, and sidekiq:
```
./script/setup
```

the script seems works fine in installing gems and setting up Redis.  however, when it gets to the step to create the postgres db I get the following error (which is a super common error with rails/postgres judging from all the stack overflow articles):
```
could not connect to server: Connection refused
	Is the server running on host "postgres" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
Couldn't create database for {"adapter"=>"postgresql", "database"=>"stream_pusher_dev", "pool"=>5, "timeout"=>5000, "username"=>"postgres", "password"=>"postgres", "host"=>"postgres", "port"=>5432}
rake aborted!
PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "postgres" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
```

this is either a problem with my local environment/docker version/setup or there is a something wrong with the rails/postgres config/volumes, as defined in `docker-compose-dev.yml`:
```
postgres:
    image: "postgres:9.4"
    ports:
      - 5432
    volumes:
      - postgres_data_9.4:/var/lib/postgresql/data
  rails:
    image: "streampusher/streampusher:latest"
    user: rails
    working_dir: /home/rails/app
    command: ./script/rails
    env_file: .env
    environment: &shared_env
      POSTGRESQL_HOST: postgres
      POSTGRESQL_PORT: 5432
      POSTGRESQL_USERNAME: postgres
      REDIS_HOST: redis
    depends_on:
      - postgres
      - redis

...

volumes:
  postgres_data_9.4:
  ```
